"""updated disease model

Revision ID: 48d729a9084f
Revises: 754a9775773d
Create Date: 2019-05-16 23:11:32.091184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d729a9084f'
down_revision = '754a9775773d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('biological_control', sa.Text(), nullable=True))
    op.add_column('diseases', sa.Column('chemical_control', sa.Text(), nullable=True))
    op.add_column('diseases', sa.Column('nutshell', sa.Text(), nullable=True))
    op.add_column('diseases', sa.Column('preventive_measures', sa.Text(), nullable=True))
    op.add_column('diseases', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('diseases', sa.Column('trigger', sa.Text(), nullable=True))
    op.drop_column('diseases', 'treatment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('treatment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('diseases', 'trigger')
    op.drop_column('diseases', 'symptoms')
    op.drop_column('diseases', 'preventive_measures')
    op.drop_column('diseases', 'nutshell')
    op.drop_column('diseases', 'chemical_control')
    op.drop_column('diseases', 'biological_control')
    # ### end Alembic commands ###
