"""added user_dir

Revision ID: 4e24855eff6a
Revises: 8895d9464c78
Create Date: 2019-05-19 13:43:01.290009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e24855eff6a'
down_revision = '8895d9464c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_dir', sa.String(length=32), nullable=False))
    op.drop_column('users', 'user_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_dir')
    # ### end Alembic commands ###
